### PR TITLE
feat: move to Pydantic 2.0 and use the 1.10 patch branch

### PR DESCRIPTION
**Pull request by math411**
*Issue #, if available:*

*Description of changes:*
Ran:
```
find src/* -type f -exec sed -i 's/from pydantic/from pydantic.v1/g' {} \;

find test/* -type f -exec sed -i 's/from pydantic/from pydantic.v1/g' {} \;
```

*Testing done:*
Passed `tox` execution and tested the branch with the SDK and Default-sim repos with similar patches. Both successfully passed `tox` executions.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by math411** [comment]
Dependent tests are expected to fail as they have version conflicts due to their dependency constraints. See testing notes for more details.

**Comment by isobelhooper** [comment]
Out of interest, is there a timeline for this PR being worked on? I'm working on a project that uses Braket (including this library and https://github.com/amazon-braket/amazon-braket-default-simulator-python) and because of these dependencies we're still limited to Pydantic v1. Would be good to be able to upgrade!

**Comment by math411** [comment]
Hi @isobelhooper and apologies for the delay.

The team is currently exploring options to make these upgrades, we will post more information in this thread when we have an update.

**Comment by math411** [comment]
Relaxing constraints in the default simulator: https://github.com/amazon-braket/amazon-braket-default-simulator-python/pull/224

**Comment by richrines1** [comment]
maybe not super elegant, but fwiw to avoid conflicts with downstream dependencies you could also use something like
```python
try:
    from pydantic.v1 import ...
except ImportError:
    from pydantic import ...
```
everywhere (at least temporarily) and just pin `pydantic >= 1.8.2` so this would work with both pydantic 1.* and 2.*

**Comment by math411** [comment]
Hi @richrines1, thank you for the suggestion. The team is going to use a slightly different release method with pinned versions to unblock this.

**Review by krneta — APPROVED** [review]

**Pull request merged**
